Deviseのサインアップ、サインイン、サインアウト機能追加
ryoji3535/chat-space pull request #4
Opened 2017-04-05 03:04 UTC by ryoji3535

2017-04-05 03:08 UTC, ryoji3535 commented
[![https://gyazo.com/c34436e82ea404547100d16d1240708c](https://i.gyazo.com/c34436e82ea404547100d16d1240708c.png)](https://gyazo.com/c34436e82ea404547100d16d1240708c)

2017-04-05 03:09 UTC, ryoji3535 commented
[![https://gyazo.com/42028cb1fc88d79ada7368a6d3ff0eee](https://i.gyazo.com/42028cb1fc88d79ada7368a6d3ff0eee.png)](https://gyazo.com/42028cb1fc88d79ada7368a6d3ff0eee)

2017-04-05 03:10 UTC, ryoji3535 commented
[![https://gyazo.com/8fab18127946fa0811d4f4c202ac33cf](https://i.gyazo.com/8fab18127946fa0811d4f4c202ac33cf.png)](https://gyazo.com/8fab18127946fa0811d4f4c202ac33cf)

2017-04-05 03:53 UTC, tetsu8dayo commented
メール認証とかいらないんだけど、やるならやって見て
haml変換とかそういうところ指摘されないようにして

2017-04-05 03:53 UTC, tetsu8dayo commented on app/controllers/application_controller.rb
> +  before_action :authenticate_user!, only: [:index]
only index でいいのですか？

2017-04-05 03:53 UTC, tetsu8dayo commented on app/views/devise/mailer/reset_password_instructions.html.erb
> +<p><%= link_to 'Change my password', edit_password_url(@resource, reset_password_token: @token) %></p>
Hamlでかく

2017-04-05 03:53 UTC, tetsu8dayo commented on app/views/devise/mailer/password_change.html.erb
> +
メーラーはいらない

2017-04-05 03:53 UTC, tetsu8dayo commented on app/views/devise/unlocks/new.html.erb
> +  </div>
Haml

2017-04-05 03:53 UTC, tetsu8dayo commented on config/environments/development.rb
>  end
なぜ追加した？
メーラーつけるならつけてもいいですが

2017-04-05 03:53 UTC, tetsu8dayo commented on db/schema.rb
> +    t.text     "name",                   limit: 65535
nameはstringでいいと思いますけど
nameにindex貼るっていう設計じゃなかったっけ

2017-04-05 03:53 UTC, tetsu8dayo commented on db/migrate/20170405014925_rename_name_column_to_name.rb
> +end
こーゆーのは作らない
ロールバックしてやり直す

2017-04-05 03:53 UTC, tetsu8dayo commented on db/migrate/20170404160807_add_name_to_users.rb
> +end
いらない
ロールバックしてやり直す

2017-04-05 03:53 UTC, tetsu8dayo commented on db/migrate/20170404144457_add_devise_to_users.rb
> +  end
なんじゃこりゃ
デバイスの仕様が変わったのかな

2017-04-05 04:00 UTC, ryoji3535 commented on app/controllers/application_controller.rb
> +  before_action :authenticate_user!, only: [:index]
最初にサインインを求められるので、indexだけでいいかと思いました。
editなどindexアクション以外のURLからなら入れてしまうことを見落としていました。
onlyを削除します。

2017-04-05 04:02 UTC, ryoji3535 commented on app/views/devise/mailer/reset_password_instructions.html.erb
> +<p><%= link_to 'Change my password', edit_password_url(@resource, reset_password_token: @token) %></p>
ビューファイルは与えられているので、与えられていない箇所は今回は不要ということですよね
削除します。

2017-04-05 04:03 UTC, ryoji3535 commented on app/views/devise/mailer/password_change.html.erb
> +
メーラーについてよく理解していなかったので、調べます。

2017-04-05 04:33 UTC, ryoji3535 commented on db/schema.rb
> +    t.text     "name",                   limit: 65535
stringで大丈夫ですね。。。
indexの意味がよくわかりません。indexを貼るというのはどういうことでしょうか。

2017-04-05 04:42 UTC, ryoji3535 commented on db/migrate/20170404144457_add_devise_to_users.rb
> +  end
これがなんなのかは理解してないです。

2017-04-05 04:44 UTC, ryoji3535 commented on db/migrate/20170405014925_rename_name_column_to_name.rb
> +end
作ってはいけないのは、要らないからですか。
nameがundefined methodと指摘されたので、Nameをnameに改名したのですが。

2017-04-06 14:17 UTC, ryoji3535 commented
[![https://gyazo.com/8bd32a1c4098640ae97885bc0c752af5](https://i.gyazo.com/8bd32a1c4098640ae97885bc0c752af5.png)](https://gyazo.com/8bd32a1c4098640ae97885bc0c752af5)

2017-04-06 16:52 UTC, ghost requested changes
indexがわからないって言ってたけどそれはダメ。
カリキュラムにもあるはずだしもうデータベース設計終わってるなら理解してるはずだけど？
わからなければ調べる。5分でできることだからやりましょう。
自分のためにコードを書いているわけだから主体性を持って取り組もう。

2017-04-06 16:52 UTC, tetsu8dayo commented on Gemfile
> +gem "devise-i18n"
これいらない気がするんだけど

2017-04-06 16:52 UTC, tetsu8dayo commented on Gemfile
> +gem "devise-i18n"
軽く調べたけどいらないね。
何やってるのか自分でわかってないのは🙅
readmeだけでも目を通しておけばこういう事態にはならないと思う
フラッシュメッセージの日本語化は主にモデルに関係するところだからviewの日本語化は関係なくない？
しかもカリキュラムで用意されてるviewを使うんだよね？ 新しいviewを導入したら面倒だよね？

2017-04-06 18:02 UTC, ryoji3535 commented on Gemfile
> +gem "devise-i18n"
よく目を通すようにします。
viewに関係するものだと思い込んで、deise フラッシュメッセージ　日本語化で検索して適当に当てはめてしまいました。
フラッシュメッセージのviewはカリキュラムでは提供されていないので、自前で作ることになっています。

2017-04-07 01:24 UTC, ryoji3535 commented
インデックス貼りました。記事を読んでいると、chat-spaceがインデックスが必要になるほどの多くの情報を検索する必要があるとは思えなかったのですが、今回は練習のために貼っているということでいいですよね。

2017-04-21 14:10 UTC, merged